"use strict";
// let user1: object[];
// let user1: object;
let userData;
userData = [];
// user1 = {nameName: "Anisul", userId: 101};
// user1= [];
let user1;
user1 = { nameName: "Anisul", userId: 101 };
userData.push(user1);
let user2;
user2 = { nameName: "Anisul", userId: 101 };
userData.push(user2);
console.log(userData);
